(function(){
var P=10000;
function q(n){var a=location.search.substring(1).split("&"),i,p;for(i=0;i<a.length;i++){p=a[i].split("=");if(decodeURIComponent(p[0]||"")===n)return decodeURIComponent((p.slice(1).join("=")||"").replace(/\+/g," "))}return null}
function platform(){var u=String(navigator.userAgent||""),p=String(navigator.platform||"");if(/Android/i.test(u))return"android";if(/iPhone|iPad|iPod/i.test(u)||(p==="MacIntel"&&Number(navigator.maxTouchPoints||0)>1))return"ios";if(/Windows/i.test(u)||/^Win/i.test(p))return"windows";if(/Macintosh|Mac OS X/i.test(u)||/^Mac/i.test(p))return"macos";if(/Linux/i.test(u)||/Linux/i.test(p))return"linux";return"unknown"}
var qa=q("account_id"),qr=q("realm")||q("game_realm"),src=q("source")||"unknown",mv=q("mod_version")||"unknown",dist=q("distribution")||"unknown";
try{if(qa)localStorage.setItem("blitz-session-account-id",qa);if(qr)localStorage.setItem("blitz-session-game-realm",qr);if(src)localStorage.setItem("blitz-session-source",src);if(mv)localStorage.setItem("blitz-session-mod-version",mv);if(dist)localStorage.setItem("blitz-session-distribution",dist)}catch(e){}
var id=qa,gr=qr;
try{if(!id)id=localStorage.getItem("blitz-session-account-id");if(!gr)gr=localStorage.getItem("blitz-session-game-realm");if(src==="unknown")src=localStorage.getItem("blitz-session-source")||src;if(mv==="unknown")mv=localStorage.getItem("blitz-session-mod-version")||mv;if(dist==="unknown")dist=localStorage.getItem("blitz-session-distribution")||dist}catch(e){}
var pf=platform(),api=String(window.BLITZ_SESSION_API||"").replace(/\/+$/,"");var er=document.getElementById("errorLine"),busy=false;
function show(m){if(er){er.textContent=m;er.className="error-line visible"}}
function clear(){if(er){er.textContent="";er.className="error-line"}}
function ready(){if(!api){show("BACKEND URL NOT SET");return false}if(!id){show("WAITING FOR ACCOUNT ID FROM HANGAR");return false}return true}
function ident(){var s="account_id="+encodeURIComponent(id);if(gr)s+="&game_realm="+encodeURIComponent(gr);s+="&source="+encodeURIComponent(src)+"&platform="+encodeURIComponent(pf)+"&distribution="+encodeURIComponent(dist)+"&mod_version="+encodeURIComponent(mv);return s}
function req(method,path,cb){if(!ready()){cb("not ready");return}var x=new XMLHttpRequest();x.onreadystatechange=function(){var d;if(x.readyState!==4)return;if(x.status<200||x.status>=300){cb("Backend HTTP "+x.status+(x.responseText?": "+x.responseText:""));return}try{d=JSON.parse(x.responseText)}catch(e){cb("Backend JSON parse error");return}if(!d||d.status!=="ok"){cb(d&&d.error?d.error:"Backend error");return}cb(null,d)};x.onerror=function(){cb("Backend network error")};var sep=path.indexOf("?")>=0?"&":"?";x.open(method,api+path+sep+"_ts="+Date.now(),true);x.send(null)}
function sum(s){var b=document.getElementById("sessionBattles"),w=document.getElementById("sessionWinRate"),a=document.getElementById("sessionAvgDamage");if(!b)return;b.textContent=String(s.battles||0);w.textContent=Number(s.win_rate||0).toFixed(2)+"%";a.textContent=String(Math.round(Number(s.avg_damage||0)))}
function tanks(ts){var l=document.getElementById("tankList"),i,t,r,n,v,j,c,st,sp;if(!l)return;l.innerHTML="";if(!ts||!ts.length){r=document.createElement("div");r.className="empty";r.textContent="Пока нет боёв после точки отсчёта.";l.appendChild(r);return}for(i=0;i<ts.length;i++){t=ts[i];r=document.createElement("div");r.className="tank";n=document.createElement("div");n.className="tank-name";n.textContent=t.name||("tank_id "+t.tank_id);r.appendChild(n);v=[[t.battles,"BATTLES"],[Number(t.win_rate||0).toFixed(2)+"%","WIN RATE"],[Math.round(Number(t.avg_damage||0)),"AVG DMG"]];for(j=0;j<v.length;j++){c=document.createElement("div");c.className="cell";st=document.createElement("strong");st.textContent=String(v[j][0]);sp=document.createElement("span");sp.textContent=v[j][1];c.appendChild(st);c.appendChild(sp);r.appendChild(c)}l.appendChild(r)}}
function refresh(){if(busy||!ready())return;busy=true;clear();req("GET","/session?"+ident(),function(e,d){busy=false;if(e){show(e);return}sum(d.session||{});tanks(d.session&&d.session.tanks||[])})}
var rb=document.getElementById("resetButton");if(rb)rb.onclick=function(){if(!ready()||!confirm("Сбросить текущую сессию?"))return;clear();req("POST","/reset?"+ident(),function(e){if(e){show(e);return}refresh()})};
refresh();setInterval(refresh,P);if(window.addEventListener){window.addEventListener("focus",refresh,false);window.addEventListener("pageshow",refresh,false);document.addEventListener("visibilitychange",function(){if(!document.hidden)refresh()},false)}
})();
